place = ('Saraguru')

print(place.lower())
print(place.upper())
print(place.capitalize())
print(place.isalpha())
print(place.islower())
print(place.title())
print(place.format())
print(place.swapcase())
print(place.find('g'))
print(place.isalnum())
print(place.isdecimal())
print(place.index('u'))
print(place.endswith('g'))
print(place.isdigit())
print(place.isspace())
print(place.join('o'))
print(place.startswith('s'))
print(place.count('r'))
print(place.rfind('r'))
print(place.rpartition('s'))